"""Init

Revision ID: 165b7dbfa7f5
Revises: 
Create Date: 2021-02-24 20:54:32.435863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165b7dbfa7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
